services:
  db:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: portfolio_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "%/XykJ|&WL4f5@4d-2"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"

  backend:
    build: ./backend
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/portfolio_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "%/XykJ|&WL4f5@4d-2"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
          VITE_API_BASE_URL: http://localhost:8080/api
          VITE_SOCKET_BASE_URL: ws://localhost:8080
    container_name: frontend
    ports:
      - "5202:80"
    depends_on:
      - backend

volumes:
  postgres_data:
